### ISSUE TITLE
Add a way to configure "pythonEnvName"

### ISSUE THREAD

**Issue by jschneider** [PrzemyslawSwiderski/python-gradle-plugin#20]
I have a monorepo with several projects that use python.

It is necessary to create a own virtual environment for each project. Therefore, I would like to configure the "pythonEnvName" for each project.
At the moment the python version is used to generate the name. I would change this to use the project name.

Maybe it is enough to remove the `internal` modifier?

**Comment by PrzemyslawSwiderski** [comment]
General idea was to store the virtual environments in the root `.gradle` so that they can be reused across different projects in the multi-project scenarios.
If you need to differentiate it per project you can possibly use `installDir` property. Please check my other comment https://github.com/PrzemyslawSwiderski/python-gradle-plugin/issues/19#issuecomment-2002598166.

**Comment by elect86** [comment]
Wouldn't it make more sense to store them under `~/.cache`, maybe?
